version: 0.2

env:
  variables:
     REPOSITORY_ECR_URI: "532336934360.dkr.ecr.us-east-1.amazonaws.com/appaccount"
     AWS_DEFAULT_REGION: "us-east-1"    
phases:
  install:
    commands:
    - echo Install started on `date`
    # Update Kube config Home Directory   
  pre_build:
    commands:
      - echo Pre Build started on `date`      
      # Start ECR
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_ECR_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
    - echo Build started on `date`    
    # Build Docker Image
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_ECR_URI:latest .
    - docker tag $REPOSITORY_ECR_URI:latest $REPOSITORY_ECR_URI:$IMAGE_TAG
    - docker tag $REPOSITORY_ECR_URI:latest $REPOSITORY_ECR_URI:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Post Build started on `date`
      # Push Docker Image
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_ECR_URI:latest
      - docker push $REPOSITORY_ECR_URI:$IMAGE_TAG
      #- docker push $REPOSITORY_ECR_URI:$CODEBUILD_BUILD_NUMBER
      # Apply manifest
      